# Generated by Django 2.2.2 on 2019-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil_name', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='customuser',
            name='perfil',
            field=models.ManyToManyField(to='users.Perfil'),
        ),
    ]
